# General
title: Altsasuko auzia | Guaixe
description: Altsasuko auziaren denbora-lerroa Guaixen argitaratutako berriei esker
author:
    name: Guaixe
    email: maketazioa@guaixe.eus
timezone: "Europe/Paris"


# Jekyll
exclude: [".rvmrc", ".rbenv-version", "Rakefile", "vendor"]
excerpt_separator: "\n"
markdown: kramdown

baseurl: 'https://guaixe.github.io/AltsasukoAuzia'
